# Generated by Django 4.2 on 2024-04-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('room', models.PositiveIntegerField(max_length=10)),
                ('exam_date', models.DateTimeField()),
                ('is_paused', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('login', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=12, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'verbose_name': 'ExamSchedule',
                'verbose_name_plural': 'ExamSchedules',
            },
        ),
    ]
