# Generated by Django 4.2 on 2024-05-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='room',
            field=models.PositiveIntegerField(),
        ),
    ]
