# Generated by Django 4.2 on 2024-05-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_schedule', '0002_alter_examschedule_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='room',
            field=models.CharField(max_length=20),
        ),
    ]
