# Generated by Django 4.2 on 2024-05-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='academic_semester',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('UZ', 'Uzbek'), ('RU', 'Russian'), ('EN', 'English'), ('KR', 'Korean')], default='UZ', max_length=7),
        ),
        migrations.AddField(
            model_name='question',
            name='specialization',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
