# Generated by Django 4.2 on 2024-05-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='name',
            field=models.CharField(blank=True, default='group', max_length=128, null=True),
        ),
    ]
