# Generated by Django 4.2 on 2024-05-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0006_remove_answer_file_alter_answer_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_ids',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
