# Generated by Django 4.2 on 2024-06-03 18:34

from django.db import migrations, models


def populate_scored_status(apps, schema_editor):
    Answer = apps.get_model('answers', 'Answer')

    for row in Answer.objects.all():
        if row.stage == 2:
            row.is_scored = True
        else:
            if row.score != 0:
                row.is_scored = True

        row.save()


class Migration(migrations.Migration):
    dependencies = [
        ('answers', '0007_answer_question_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_scored',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populate_scored_status),
    ]
