# Generated by Django 4.2 on 2024-06-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0008_answer_is_scored'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
