# Generated by Django 4.2 on 2024-05-14 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subject_code'),
        ('teachers_subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersubject',
            name='subject_code',
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject'),
        ),
    ]
