# Generated by Django 4.2 on 2024-05-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_subjects', '0002_remove_teachersubject_subject_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubject',
            name='language',
            field=models.CharField(choices=[('UZ', 'Uzbek'), ('RU', 'Russian'), ('EN', 'English')], default='UZ', max_length=7),
        ),
    ]
