from apps.main.answers.services.create_answer_to_db_case1_3 import create_answer_case_1_3
from apps.main.answers.services.create_answer_to_db_case2 import create_answer_to_db_case_2
from apps.main.answers.services.get_answer_case_1 import get_answer_from_db_to_case_1
from apps.main.answers.services.get_answer_case_3 import get_answer_from_db_to_case_3
# from apps.main.answers.services.get_answer_case_2 import get_answer_from_db_to_case_2