# Generated by Django 4.2 on 2024-05-24 18:36

import apps.main.teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20240523_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='login',
            field=models.CharField(default=apps.main.teachers.models.generate_random_username, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(default=apps.main.teachers.models.generate_random_password, max_length=6, unique=True),
        ),
    ]
