from apps.main.teachers.services.teacher_login_service import teacher_login_data_checker
from apps.main.teachers.services.teacher_student_make_score_servvice import teacher_make_score_to_student
from apps.main.teachers.services.teacher_student_service import teacher_student_picker