from apps.main.teachers.services.teacher_login_service import teacher_login_data_checker
from apps.main.teachers.services.teacher_set_score_to_student_service import set_score_to_student
from apps.main.teachers.services.teacher_student_service import teacher_student_list
from apps.main.teachers.services.teacher_comment_to_student import write_comment_to_student, get_comment_from_db