# Generated by Django 4.2 on 2024-05-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_group',
            field=models.CharField(default='KIUT', max_length=25),
            preserve_default=False,
        ),
    ]
