# Generated by Django 4.2 on 2024-05-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_student_group_student_direction_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='direction_id',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='group_id',
            new_name='group',
        ),
    ]
